[package]
name = "netrex"
version = "0.1.0"
authors = ["Bavfalcon9"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Hard depend on binary_utils
binary_utils = { git = "https://github.com/NetrexMC/BinaryUtil", branch = "master" }
flate2 = { version = "1.0.20", features = ["zlib"] }
rakrs = { git = "https://github.com/NetrexMC/RakNet", branch = "master" }
mcpe_protocol = { git = "https://github.com/NetrexMC/Protocol", branch = "master" }
simplelog = "0.10.0"
log = "0.4.14"