networking:
  # Whether or not to enable encrypted networking traffic
  # This will add a little overhead, but it's usually not noticiable.
  # ! This is required for featured servers
  encryption: true
  # Whether or not to validate xbox-live logins
  # Disabling this will allow any players to join your server, regardless if
  # they are logged in or not.
  # ! Option required for featured servers
  xbox-auth: true
resources:
  # This currently does nothing.
  enabled: false
  # The packs folder
  pack-folder: /resourcepacks
