[package]
name = "codegen"
version = "0.1.0"
edition = "2021"
private = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.29"
quote = "1.0.10"
syn = { version = "1.0.80", features = [ "full" ] }