name: Build Tests
on: [push]

jobs:
  test:
    name: Test Nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly   
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: test
  build:
    name: Build Nightly
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '-build')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly   
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: build
          args: --release --all-features 
